### ISSUE TITLE
Run extensive tests on 0.2.0 qpc-tools release

### ISSUE THREAD

**Issue by kholdaway** [quipucords/qpc-tools#47]

**Comment by myersCody** [comment]
Since we are testing for the release, everything should be tested from an rpm or the release workflow. 

-----

#### Test One: New CLI Args (Online)
@myersCody 

- [x] RHEL8 
- [x] RHEL7 
- [x] CentOS 7 
- [x] CentOS 6 
- [x] RHEL6 

**Server:** 
Testing args: (version, home-dir, port, username & password)
```
mkdir /testing/
qpc-tools server install --version 0.9.1 --home-dir=/testing --port 7993 --username AshLovesOwls --password owlMcOwlFace --db-user cmoney --db-password asdf 
```
 **CLI:** 
Testing args:  (version, home-dir, server-host & server-port on CLI)
```
mkdir /testing/
qpc-tools cli install --version 0.9.1 --home-dir=/testing --server-host 127.0.0.1 --server-port 7993 
```

---

#### Test Two: New CLI Args (Offline)
@abaiken 

- [x] RHEL8 
- [x] RHEL7 
- [x] CentOS 7 
- [x] CentOS 6 
- [x] RHEL6 

⚠️ You should be prompted for passwords.

- [x]  Additionally check to make sure your passwords are masked in the logs

**Server:** 
Testing args: (version, home-dir, port, username)
```
mkdir /testing/
qpc-tools server install --version 0.9.1 --home-dir=/testing --port 7993 --username admin --db-user testMe --offline-files /qpc_tools/install/packages
```
 **CLI:** 
Testing args:  (version, home-dir, server-host & server-port on CLI)
```
mkdir /testing/
qpc-tools cli install --version 0.9.1 --home-dir=/testing --server-host 127.0.0.1 --server-port 7993 --offline-files /qpc_tools/install/packages
```
---

#### Test Three: Testing upgrading (old installer to new installer)
@myersCody 

- [x] RHEL7
- [x] CentOS 7
- [x] CentOS 6
- [x] RHEL6

Found a bug: https://github.com/quipucords/qpc-tools/issues/57
**Install 0.9.0**
```
make setup
wget -O - https://github.com/quipucords/qpc-tools/releases/download/0.1.1/quipucords_install.tar.gz >> quipucords_install.tar.gz
tar -xzvf quipucords_install.tar.gz
cd install; ./install.sh -e server_version=0.9.0 -e cli_version=0.9.0
```
Add some data: 

 - [x] VScan 
```
qpc scan start --name VScan
qpc scan job --id 1
```

**Install 0.9.1**
```
qpc-tools server install --db-password password --password pass
qpc-tools cli install --version 0.9.1 --server-host 127.0.0.1 --server-port 9443
```
---

#### Test Four: Testing upgrading
@kholdaway 

- [x] RHEL7 
- [x] CentOS 7 
- [x] CentOS 6  - WORKS if you use --password=pass --db-password=password for both installs
- [x] RHEL6 - WORKS if you use --password=pass --db-password=password for both installs

```
qpc-tools cli install --version 0.9.0
qpc-tools server install --version 0.9.0
Add some data to the docker DB (use post install script to populate data, run a vcenter scan)
```
 - [x] VScan 

```
qpc-tools cli install --version 0.9.1
qpc-tools server install --version 0.9.1 
Verify that data is still there and works (e.g. the passwords can be decrypted, vcenter scan runs again)
```
---

#### Test Five: Test advanced args
@abaiken 
- [x] RHEL7 
- [x] CentOS 7 
- [x] CentOS 6  
- [x] RHEL6 
- [x] RHEL8 (fails with use_docker=True and use_supervisord=False (as expected) but advanced args works properly


```
qpc-tools server install --advanced use_docker=True use_supervisord=False
qpc-tools cli install --advanced ansible_log_level=10
```

---

#### Test Six: Test Manpage
@myersCody 

- [x] man qpc-tools

**Comment by kholdaway** [comment]
All tests passed
